name: 💿 St2_FINAL_Build
on:
  workflow_dispatch:
    inputs:
      model:
        description: "设备型号"
        required: true
        default: "bdkj-bd-one"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses-dev libssl-dev python3

      - name: Download iStoreOS ImageBuilder
        run: |
          wget https://github.com/istoreos/istoreos/releases/download/istoreos-24.10/istoreos-imagebuilder-24.10-rockchip-armv8.tar.xz
          tar -xf istoreos-imagebuilder-*.tar.xz
          mv istoreos-imagebuilder-* ib

      - name: Run your build script
        run: |
          chmod +x arm64/build24.sh
          cd ib
          ../arm64/build24.sh

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: my-final-firmware
          path: ib/bin/targets/rockchip/armv8/*.img.gz
