name: 💿 St2_FINAL_Build
on:
  workflow_dispatch:
    inputs:
      model:
        description: "设备型号"
        required: true
        default: "bdkj-bd-one"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses-dev libssl-dev python3

      - name: Download iStoreOS ImageBuilder
        run: |
          wget https://codeload.github.com/istoreos/istoreos/tar.gz/refs/tags/v24.10.0-rc5.tar.gz -O istoreos-v24.10.0-rc5.tar.gz
          tar -xf istoreos-v24.10.0-rc5.tar.gz
           mv istoreos-* ib

      - name: Run your build script
        run: |
          chmod +x arm64/build24.sh
          cd ib
          ../arm64/build24.sh

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: my-final-firmware
          path: ib/bin/targets/rockchip/armv8/*.img.gz
